// Generated by Copilot
const { test, expect } = require('@playwright/test');

const REFERENCE_CONFIG = {
  amplitudeCm: 2.0,
  peaks: 7,
  ballDiameterCm: 4.8,
  ballMassG: 450,
  trackLengthCm: 100,
  muR: 0.002,
  cw: 0.47,
  magnetForceN: 10.0,
  timerMs: 40,
  sensorRangeCm: 4.0,
  magnetEnabled: true,
};

const FIXED_DT = 1 / 240;
const DEFAULT_SAMPLE_STEPS = 1200;
const SIMULATION_URL = '/Sim&Real/Sim-Kugelbahn-w-Magnet.html?test=1';

async function openSimulation(page) {
  await page.goto(SIMULATION_URL);
  await expect.poll(() => page.evaluate(() => Boolean(window.__simulationTest))).toBe(true);
}

async function runSamples(page, configuration, steps = DEFAULT_SAMPLE_STEPS) {
  return page.evaluate(
    ({ configuration, steps }) => {
      const initial = window.__simulationTest.configure(configuration);
      const samples = window.__simulationTest.sample(steps);
      return { initial, samples };
    },
    { configuration, steps },
  );
}

function expectFiniteTelemetry(samples) {
  for (const sample of samples) {
    expect(Number.isFinite(sample.time)).toBe(true);
    expect(Number.isFinite(sample.state.s)).toBe(true);
    expect(Number.isFinite(sample.state.x)).toBe(true);
    expect(Number.isFinite(sample.state.y)).toBe(true);
    expect(Number.isFinite(sample.state.v)).toBe(true);
    expect(Number.isFinite(sample.forces.normal)).toBe(true);
    expect(Number.isFinite(sample.forces.centrifugal)).toBe(true);
    expect(Number.isFinite(sample.energy.current)).toBe(true);
    expect(Number.isFinite(sample.energy.loss)).toBe(true);
    expect(Number.isFinite(sample.energy.magnetWork)).toBe(true);
    expect(Number.isFinite(sample.energy.residual)).toBe(true);
  }
}

test('reference run produces continuous telemetry and preserves the energy balance', async ({ page }) => {
  await openSimulation(page);
  const { initial, samples } = await runSamples(page, REFERENCE_CONFIG);

  expect(samples).toHaveLength(DEFAULT_SAMPLE_STEPS);
  expectFiniteTelemetry([initial, ...samples]);
  expect(initial.config).toMatchObject({
    amplitude: 0.02,
    peaks: 7,
    ballDiameter: 0.048,
    ballMass: 0.45,
    trackLength: 1,
    muR: 0.002,
    cw: 0.47,
    magnetForce: 10,
    timerMs: 40,
    sensorRange: 0.04,
    magnetEnabled: true,
  });

  for (let index = 0; index < samples.length; index++) {
    const sample = samples[index];
    expect(sample.time).toBeCloseTo((index + 1) * FIXED_DT, 10);
    expect(sample.state.s).toBeGreaterThanOrEqual(sample.boundaries.startS - 1e-12);
    expect(sample.state.s).toBeLessThanOrEqual(sample.boundaries.endS + 1e-12);
    expect(sample.state.x).toBeGreaterThanOrEqual(-1e-12);
    expect(sample.state.x).toBeLessThanOrEqual(1 + 1e-12);

    const expectedCentrifugal = sample.state.curvatureRadius === null ? 0 : ((REFERENCE_CONFIG.ballMassG / 1000) * sample.state.v ** 2) / sample.state.curvatureRadius;
    expect(sample.forces.centrifugal).toBeCloseTo(expectedCentrifugal, 10);
    expect(sample.forces.normal).toBeGreaterThanOrEqual(-1e-12);
    expect(sample.energy.current).toBeCloseTo(sample.energy.kinetic + sample.energy.potential, 10);
    expect(Math.abs(sample.energy.residual)).toBeLessThan(0.002);
  }

  expect(samples.some((sample) => sample.magnets.some((magnet) => magnet.active))).toBe(true);
  expect(samples.some((sample) => sample.energy.magnetWork > 0)).toBe(true);
});

test('UI parameters map to SI configuration and reset the telemetry clock', async ({ page }) => {
  await openSimulation(page);
  const result = await page.evaluate((configuration) => {
    const configured = window.__simulationTest.configure(configuration);
    const afterStep = window.__simulationTest.step();
    const afterReset = window.__simulationTest.reset();
    return { configured, afterStep, afterReset };
  }, REFERENCE_CONFIG);

  expect(result.configured.config).toMatchObject({
    amplitude: 0.02,
    peaks: 7,
    ballDiameter: 0.048,
    ballMass: 0.45,
    trackLength: 1,
    sensorRange: 0.04,
  });
  expect(result.afterStep.time).toBeCloseTo(FIXED_DT, 10);
  expect(result.afterReset.time).toBe(0);
  expect(result.afterReset.energy.current).toBeCloseTo(result.afterReset.energy.initial, 10);
});

test.describe('simulation parameter regressions', () => {
  const cases = [
    {
      name: 'booster disabled',
      configuration: { ...REFERENCE_CONFIG, magnetEnabled: false },
      check: (samples) => {
        expect(samples.every((sample) => sample.magnets.every((magnet) => !magnet.active))).toBe(true);
        expect(samples.at(-1).energy.magnetWork).toBe(0);
      },
    },
    {
      name: 'higher rolling friction accumulates losses',
      configuration: { ...REFERENCE_CONFIG, muR: 0.005 },
      check: (samples) => expect(samples.at(-1).energy.loss).toBeGreaterThan(0),
    },
    {
      name: 'short track remains inside its configured boundary',
      configuration: { ...REFERENCE_CONFIG, trackLengthCm: 50 },
      check: (samples) => {
        expect(samples.every((sample) => sample.state.x >= -1e-12 && sample.state.x <= 0.5 + 1e-12)).toBe(true);
        expect(samples.some((sample) => sample.boundaries.clampedThisStep)).toBe(true);
      },
    },
  ];

  for (const testCase of cases) {
    test(testCase.name, async ({ page }) => {
      await openSimulation(page);
      const { samples } = await runSamples(page, testCase.configuration);
      expectFiniteTelemetry(samples);
      testCase.check(samples);
    });
  }
});
