# Generated by Copilot
from pathlib import Path


REQUIRED_KEYS = ("WIFI_SSID", "WIFI_PASSWORD")


def read_dotenv(path):
    values = {}
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue

        key, separator, value = line.partition("=")
        if not separator or not key.strip():
            raise ValueError(f"Invalid .env entry on line {line_number}")

        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('\"', "'"):
            value = value[1:-1]
        values[key] = value

    return values


def as_cpp_string(value):
    escaped_value = value.replace("\\", "\\\\").replace('\"', '\\"')
    return f'\\"{escaped_value}\\"'


Import("env")

project_dir = Path(env.subst("$PROJECT_DIR"))
dotenv_path = project_dir / ".env"
if not dotenv_path.exists():
    raise FileNotFoundError(f"Missing {dotenv_path}. Copy example.env to .env and fill in the credentials.")

dotenv_values = read_dotenv(dotenv_path)
missing_keys = [key for key in REQUIRED_KEYS if not dotenv_values.get(key)]
if missing_keys:
    missing = ", ".join(missing_keys)
    raise ValueError(f"Missing required .env value(s): {missing}")

env.Append(
    CPPDEFINES=[
        (key, as_cpp_string(dotenv_values[key]))
        for key in REQUIRED_KEYS
    ]
)
